### ISSUE TITLE
is this library support .ogg audio file format?

### ISSUE THREAD

**Issue by calvinsug** [tbaranes/AudioPlayerSwift#23]
I'm looking for a audio library for swift which support .ogg audio file format. Just want to make sure if this library support it or not ?

**Comment by tbaranes** [comment]
The library is fully based on `AVFoundation`, so if `AVFoundation` supports it, it will, otherwise no. So right now, I can't tell if it will work or no, but you can give it a try by replacing the audio files in the demo app and see how it goes. Don't hesitate to tell here the result if you give it a try!

**Comment by calvinsug** [comment]
i think it doesnt work, because AVFoundation does not support ogg file

**Comment by tbaranes** [comment]
Sorry to heard that. Closing now, I don't plan to quit AVFoundation so, I don't think ogg will be supported anytime soon.
